services:
  thymeleaf_application:
    container_name: thymeleaf_application
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
#    depends_on:
#      - database
    ports:
      - "8181:8181"
#    networks:
#      - blog_post_network
    restart: on-failure:10
#  database:
#    container_name: thymeleaf_application_database
#    image: mysql:latest
#    hostname: mvc_blog
#    restart: unless-stopped
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=user
#      - MYSQL_DATABASE=mvc_blog
#      - MYSQL_ROOT_PASSWORD=1234
#    networks:
#      - blog_post_network
#networks:
#  blog_post_network:
#    driver: bridge

networks:
  default:
    driver: bridge